name: Publish to WinGet
env:
  PUB_KEY: ${{ secrets.PUB_KEY }}
  SERVERS: ${{ vars.SERVERS }}
  API_SERVERS: ${{ vars.API_SERVERS }}
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: RustDesk.RustDesk
          version: "1.4.5"
          release-tag: "1.4.5"
          token: ${{ secrets.WINGET_TOKEN }}
